### PR TITLE
Hand in alll the excercises

### PR DESCRIPTION
**Pull request by Aphyllanthes**
My exercises are in the Folder called "Nele" inside the WS18 folder. For the map we have to hand in I created a shiny-app. To see the map, you have to run the "app.R" file. Inside this app, there are also included the two sql-exercises. 
The Hobo-report in the file Hobo.pdf, and the report about the function is in the CCD_Index file.
My name and Matrikelnr are listed in the Hobo.pdf as well as in the CCD_Index.pdf.  I hope this is an apropriate and valid vay to hand in all the tasks.
Thank you for the lectures, I learned a lot!

### CODE REVIEW

**Comment by modche** [comment]
Hi. At least we can confirm that you submit your files/exercises on time! But merging this pull request does not really make sense for me. However, we have your submission, thats good.

**Comment by modche** [comment]
Downloaded all files from your forked repository.

**Comment by mmaelicke** [comment]
Nice work! Thanks a lot for your participation.

**Comment by Aphyllanthes** [comment]
So to pull my fork, I should have deleted all the files I added to the climate-indeces folder? I am sorry, I didnt realise the files were there again. Now, that I deleted the files I could crate a new pull request and you would accept it? 
But if you already downloaded my work anyway, there is probably no need to create a new pull request. I will try it anyway, but I will totaly understand if you don't want to react and respond to it anymore.
Sorry that I caused this trouble!

**Pull request closed without merging**
